on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ./hello.sh
        echo Hi,
        echo Welcome.
