on:
  push:
    branches:
      - 'main'
      - 'branch_1'
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, closed]
    branches:
      - 'main'
      - 'branch_1'
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ./hello.sh
        echo Hi,
        echo Welcome.
