on:
  push:
    branches:
    - master
    - branch_1
  pull_request:
    branches:
    - master
    - branch_1
    types: [assigned, opened, synchronize, reopened, closed]
jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2.7 and pypy3.9
      matrix:
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ./hello.sh
        ./check.sh
        echo Hi,
        echo Welcome.
